In this week, we are going to: 
1) import pandas library to the notebook
2) reading the data set

# Import

In [2]:
# first of all, we have to import pandas library

import pandas as pd

# Next, we can use the 'pd' term to call the pandas library

# Reading data set

In [4]:
# pd.read_csv('data file name.suffix')
# suffix can be csv, xlsx, table, etc.
# we have to define a variable to store the data set.

data_frame = pd.read_csv('train.csv')
data_frame

,id,Sex,Length,Diameter,Height,Whole weight,Whole weight.1,Whole weight.2,Shell weight,Rings
0,0,F,0.550,0.430,0.150,0.7715,0.3285,0.1465,0.2400,11
1,1,F,0.630,0.490,0.145,1.1300,0.4580,0.2765,0.3200,11
2,2,I,0.160,0.110,0.025,0.0210,0.0055,0.0030,0.0050,6
3,3,M,0.595,0.475,0.150,0.9145,0.3755,0.2055,0.2500,10
4,4,I,0.555,0.425,0.130,0.7820,0.3695,0.1600,0.1975,9
...,...,...,...,...,...,...,...,...,...,...
90610,90610,M,0.335,0.235,0.075,0.1585,0.0685,0.0370,0.0450,6
90611,90611,M,0.555,0.425,0.150,0.8790,0.3865,0.1815,0.2400,9
90612,90612,I,0.435,0.330,0.095,0.3215,0.1510,0.0785,0.0815,6
90613,90613,I,0.345,0.270,0.075,0.2000,0.0980,0.0490,0.0700,6
90614,90614,I,0.425,0.325,0.100,0.3455,0.1525,0.0785,0.1050,8

In [ ]:
# if data file was not in a current folder, we can copy the path of the folde which consists the data file, then add file name end of the path.

# df = pd.read_csv(r'path\file name.suffix')